### ISSUE TITLE
manual testing for Sprint 3

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#105]
# TESTING.md
[TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/test/TESTING.md)

# Windows

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependancies for the project from LOCAL #30
- [x] implement REPL thingy #66
- [x] IDEA should remember that some modules were previously installed #64

# Linux

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependancies for the project from LOCAL #30
- [x] implement REPL thingy #66
- [x] IDEA should remember that some modules were previously installed #64

# Mac

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependancies for the project from LOCAL #30
- [x] implement REPL thingy #66
- [x] IDEA should remember that some modules were previously installed #64
