### ISSUE TITLE
manual testing for Sprint 4

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#106]
# TESTING.md
[TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/test/TESTING.md)

# Windows

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependancies for the project from LOCAL #30
- [ ] implement REPL thingy #92
- [x] Import IDE settings from remote #117
- [x] IDEA should remember that some modules were previously installed #64

# Linux

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependancies for the project from LOCAL #30
- [x] implement REPL thingy #92
- [x] Import IDE settings from remote #117
- [x] IDEA should remember that some modules were previously installed #64

# Mac

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependancies for the project from LOCAL #30
- [x] implement REPL thingy #92
- [x] Import IDE settings from remote #117
- [x] IDEA should remember that some modules were previously installed #64

**Comment by superseacat** [comment]
eventually, plugin must be compatible with the current version of IDEA so to show in the plugin search results!

**Comment by superseacat** [comment]
issue: **Part 2.2. REPL configuration dialog is shown, checkbox unchecked, valid changes**
