### ISSUE TITLE
manual testing for Sprint 5

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#137]
# TESTING.md
[TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/test/TESTING.md)

# Windows

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] **implement REPL thingy #92**
- [ ] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

# Linux

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] implement REPL thingy #92
- [ ] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

# Mac

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] implement REPL thingy #92
- [ ] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

**Comment by superseacat** [comment]
the fun seems to begin here: so on IJ IC 2020.1 the plugin installed wo restart, but at the same time, the "A+ Menu" did not show and the modules did not load... 
 
![Screenshot from 2020-04-24 13-18-02](https://user-images.githubusercontent.com/9991098/80202314-18264400-862e-11ea-882a-2c04cadb6adb.png)

**Comment by superseacat** [comment]
todo: check the case when the scala plugin is not installed, thus try using some of the func
