### ISSUE TITLE
manual testing for Sprint 6

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#148]
# TESTING.md
[TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/test/TESTING.md)

cleanup for:
* [Ubuntu (VDI)](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-579616500)
* [Mac](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-581294152)

- [ ] **PR to `master` created**

# Windows

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] **implement REPL thingy #92**
- [x] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

# Linux

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] implement REPL thingy #92
- [x] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

# Mac

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] implement REPL thingy #92
- [x] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

**Comment by OlliKiljunen** [comment]
Notes for Windows:
```
# Initialization

Generated .zip with ./gradlew buildPlugin on master

# Windows 10

## Setup

Windows 10 VDI
Installed IntelliJ IDEA
Installed plugin from disk
Downloaded Zulu OpenJDK 11 x64
New Project -> Java
    JDK set
Indexing takes a long time

## making hints on missing plugins #9

Restarted IDE
!!! NO SCALA PLUGIN NOTIFICATION !!!
Installed Scala plugin from marketplace
Restarted IDE
No Scala plugin notification (as expected)
Scala plugin disabled
Restarted IDE
!!! NO SCALA PLUGIN NOTIFICATION !!!
Enabled Scala plugin
Restarted IDE
No Scala plugin notification (as expected)

## add new startup notification saying the plugin is in beta/dev #44

The notification of that says plugin is under development is shown

## install required dependencies for the project from LOCAL #30

Created a new project
!! TESTING.md is out of date. !!
    Have to turn project into A+ project first
! The image in TESTING.md is missing lib directory !

## implement REPL thingy #92

!! TESTING.md is out of date. !!
    Have to turn project into A+ project first
    Step 2.2. should be removed
Running Scala REPL in the first time takes a long time
! Image in Step 2.3.iii doesn't match the instructions of the previous step !
! Part 2.4. is redundant (cf. 2.1.iv) !


## turn project into "A+ O1" project" feature #86

! More detailed steps would be useful !
    Especially, how to get to the initial state (reset settings)
!! There should be better instructions on how to execute step 11. !!
! What I should observe on step 12. !

## Renaming/removing module files leads to incorrect states in module list #110

!! TESTING.md is out of date. !!
    Have to turn project into A+ project first
    
## Renaming/removing module files leads to incorrect states in module list #110

!!! After part 3, the modules don't compile !!!

## Resetting A+ Courses Settings

! Have to start with a new project because the previous test left the project in a bad state !
```

Notes for Ubuntu
```
when turned to A+ project (settings not imported) the project is reloaded even though that might be unnecessary
the dialog "Adjust Intellij IDEA Settings" should explain more explicitely what's gonna happen
  !!! cancelling the dialog should do nothing !!!
Modules panel should be invisible until project is turned to an A+ project
UI enhancement idea: Icon for topmost A+ menu
What should happen when project is turned to an a+ project but restart is opted out
    (It seems that the project is reloaded still)
    The menu item should be grayed out. (Also after restart.)
Turning project into A+ project: "Restart or not?" What should closing the dialog (cancelling) do?
Removed scala sdk, reinstalled module, have to do that twice before they are marked installed.
    IML files are modifies when modules are removed.
```
