### ISSUE TITLE
manual testing for Sprint 7

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#187]
# TESTING.md
[TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/test/TESTING.md)

cleanup for:
* [Ubuntu (VDI)](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-579616500)
* [Mac](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-581294152)

- [ ] **PR to `master` created**

# Windows

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] **implement REPL thingy #92**
- [x] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

# Linux

- [x] making hints on missing plugins #9
- [x] add new startup notification saying the plugin is in beta/dev #44
- [x] install required dependencies for the project from LOCAL #30
- [x] implement REPL thingy #92
- [x] persistant setting for REPL (show dialog)
- [x] Import IDE settings from remote #117
- [x] Import project settings from remote #118
- [x] Scala SDK is installed
- [x] removing O1 marks other modules invalid

# Mac

- [ ] making hints on missing plugins #9
- [ ] add new startup notification saying the plugin is in beta/dev #44
- [ ] install required dependencies for the project from LOCAL #30
- [ ] implement REPL thingy #92
- [ ] persistant setting for REPL (show dialog)
- [ ] Import IDE settings from remote #117
- [ ] Import project settings from remote #118
- [ ] Scala SDK is installed
- [ ] removing O1 marks other modules invalid

**Comment by OlliKiljunen** [comment]
Followed the new TESTING.md (PR #223).

As previously, "missing Scala plugin" notification is not shown. This was addressed earlier in #181 but it was closed for a good reason. However, turned out there is an error if Scala plugin is not installed when project is turned into an A+ project. Created an issue for that: #224.

**Comment by superseacat** [comment]
done as a part of https://github.com/Aalto-LeTech/intellij-plugin/issues/225
