### ISSUE TITLE
productization tasks pool

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#218]
* [x]  **updating all possible components and dependencies to the latest version (maybe apart from the intellij plugin :wink: ) take this https://github.com/Aalto-LeTech/intellij-plugin/issues/94 into account as well** #231 
* [x]  visuals to JB plugins page
* [ ]  docs https://github.com/Aalto-LeTech/intellij-plugin/issues/104
* [x]  **proof-reading of the texts (https://github.com/Aalto-LeTech/intellij-plugin/issues/186)**
* [ ] "the plugin developers haven't implemented the feature" (reporting errors from the IDE error monitoring and tracking (an example: https://github.com/Aalto-LeTech/intellij-error-reporting ) #359
* [ ] general logging and monitoring #358 
* [ ] "the package pushed to github repo is invalid" https://github.com/Aalto-LeTech/intellij-plugin/issues/127
* [x] **UI/UX evaluation (+ testing) #230 & #266**
* [ ] videos of the usage (https://plugins.jetbrains.com/plugin/13634-a-courses/custom-pages)
* [x] **maintenance model (to write out) #232**
