### ISSUE TITLE
manual testing for Sprint #8

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#225]
# TESTING.md
[TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/test/TESTING.md)

cleanup for:
* [Ubuntu (VDI)](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-579616500)
* [Mac](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-581294152)

- [ ] **PR to `master` created**

# Windows

- [x] [1 Install A+ Courses plugin](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#1-install-a-courses-plugin)
- [x] [2 Initialize a new project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#2-initialize-a-new-project)
- [x] [3 Observe startup notification](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#3-observe-startup-notification)
- [ ] [4 Observe Scala plugin notification](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#4-observe-scala-plugin-notification)
- [x] [5 About window](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#5-about-window)
- [x] [6 Turn project into A+ project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#6-turn-project-into-a-project)
- [x] [7 Importing modules](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#7-importing-modules)
- [x] [8 Using Scala REPL](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#8-using-scala-repl)
- [x] [9 Removing a module](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#9-removing-a-module)

# Linux

- [x] [1 Install A+ Courses plugin](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#1-install-a-courses-plugin)
- [x] [2 Initialize a new project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#2-initialize-a-new-project)
- [x] [3 Observe startup notification](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#3-observe-startup-notification)
- [ ] [4 Observe Scala plugin notification](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#4-observe-scala-plugin-notification)
- [x] [5 About window](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#5-about-window)
- [x] [6 Turn project into A+ project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#6-turn-project-into-a-project)
- [x] [7 Importing modules](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#7-importing-modules)
- [x] [8 Using Scala REPL](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#8-using-scala-repl)
- [x] [9 Removing a module](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#9-removing-a-module)

# Mac

- [x] [1 Install A+ Courses plugin](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#1-install-a-courses-plugin)
- [x] [2 Initialize a new project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#2-initialize-a-new-project)
- [x] [3 Observe startup notification](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#3-observe-startup-notification)
- [ ] [4 Observe Scala plugin notification](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#4-observe-scala-plugin-notification)
- [x] [5 About window](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#5-about-window)
- [x] [6 Turn project into A+ project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#6-turn-project-into-a-project)
- [x] [7 Importing modules](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#7-importing-modules)
- [x] [8 Using Scala REPL](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#8-using-scala-repl)
- [x] [9 Removing a module](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#9-removing-a-module)

**Comment by superseacat** [comment]
a simple idea for required plugins notifications: move them higher in the initialization activity

**Comment by superseacat** [comment]
testing on **Linux** is now a bit different with VDI -> box has the IDEA 2020.1 with some older version of our plugin :smile:

**Comment by superseacat** [comment]
we need to do something with Scala Plugin missing notification, otherwise OK
