### ISSUE TITLE
Pre-release manual testing

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#266]
# TESTING.md
[TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/test/TESTING.md)

cleanup for:
* [Ubuntu (VDI)](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-579616500)
* [Mac](https://github.com/Aalto-LeTech/intellij-plugin/issues/18#issuecomment-581294152)

- [ ] **PR to `master` created**

# Windows

- [x] [1 Install A+ Courses plugin](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#1-install-a-courses-plugin)
- [x] [2 Initialize a new project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#2-initialize-a-new-project)
- [x] [3 About window](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#5-about-window)
- [x] [4 Turn project into A+ project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#6-turn-project-into-a-project)
- [x] [5 Importing modules](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#7-importing-modules)
- [x] [6 Using Scala REPL](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#8-using-scala-repl)
- [x] [7 Removing a module](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#9-removing-a-module)
- [x] [8 Authentication with A+ LMS]()
- [x] [9 Assignments submission]()
- [x] [10 Refreshing Modules and Assignments]()
- [x] [11 Checking the submission]()

# Linux

- [x] [1 Install A+ Courses plugin](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#1-install-a-courses-plugin)
- [x] [2 Initialize a new project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#2-initialize-a-new-project)
- [x] [3 About window](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#5-about-window)
- [x] [4 Turn project into A+ project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#6-turn-project-into-a-project)
- [x] [5 Importing modules](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#7-importing-modules)
- [x] [6 Using Scala REPL](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#8-using-scala-repl)
- [x] [7 Removing a module](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#9-removing-a-module)
- [x] [8 Authentication with A+ LMS]()
- [x] [9 Assignments submission]()
- [x] [10 Refreshing Modules and Assignments]()
- [x] [11 Checking the submission]()

# Mac

- [x] [1 Install A+ Courses plugin](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#1-install-a-courses-plugin)
- [x] [2 Initialize a new project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#2-initialize-a-new-project)
- [x] [3 About window](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#5-about-window)
- [x] [4 Turn project into A+ project](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#6-turn-project-into-a-project)
- [x] [5 Importing modules](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#7-importing-modules)
- [x] [6 Using Scala REPL](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#8-using-scala-repl)
- [x] [7 Removing a module](https://github.com/Aalto-LeTech/intellij-plugin/blob/rewrite-testing-md/TESTING.md#9-removing-a-module)
- [x] [8 Authentication with A+ LMS]()
- [x] [9 Assignments submission]()
- [x] [10 Refreshing Modules and Assignments]()
- [x] [11 Checking the submission]()

**Comment by superseacat** [comment]
* right-click on **Module** shows both: **download** and **refresh modules** - I think should be only **download**
* text is too similar here, feels like a duplicate - I suggest rewording
```
Submission feedback available Feedback for Assignment 2 (Goodstuff) is now available. 
Click the link below to open the feedback.

Click here to open the feedback.
```

* REPL for ... icon and one inside RunConfiguration should be with accent pink

* `NPE` is thrown if the default module (O1Module) is missing - no surprise, but IDEA considers `NPE` a fatal error, and that proposes to disable plugin :laughing: 

* there is some mystical process of how `a-plus-project.json` is being overridden, but hopefully https://github.com/Aalto-LeTech/intellij-plugin/pull/317 solves it (I'd still discuss that part of the logics in detail) @nikke234 

* created an SBT project, made it A+, got the error with `project disposed`, but could not reprocude later @OlliKiljunen

**Comment by superseacat** [comment]
* [ ] r-click **Import  A+ Module** on "[installed]" module feels awkward
* [ ] **SwingExamples** and **O1** both physically contain `scala-swing_2.13-2.1.1.jar`
* [ ] login keyring issue on Aalto Ubuntu

**Comment by superseacat** [comment]
apart from minor differences in look-and-feel between Mac and other OS's and a weird "JAVA" started along with REPL everything worked for mac
